version: '3.7'

services:
  api:
    container_name: gif-api
    build:
      context: .
      target: base-container
    volumes:
      - .:/home/node/
      - /home/node/node_modules
    ports:
      - 3333:3333
    command: npm run start:api
    networks:
      - webnet
  frontend:
    container_name: gif-frontend
    build:
      context: .
      target: base-container
    volumes:
      - .:/home/node/
      - /home/runner/node_modules
    ports:
      - 4200:4200
    command: npm run start:frontend
    networks:
      - webnet
    depends_on:
      - api
networks:
  webnet:
